## Numpy Library Nots :

In [1]:
import numpy as np
arr = np.array([23,23,24,12,21,22])
arr

array([23, 23, 24, 12, 21, 22])

In [9]:
arr = np.zeros((3,4))
arr
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [16]:
arr = np.linspace(1,43,30)
arr.round(1)

array([ 1. ,  2.4,  3.9,  5.3,  6.8,  8.2,  9.7, 11.1, 12.6, 14. , 15.5,
       16.9, 18.4, 19.8, 21.3, 22.7, 24.2, 25.6, 27.1, 28.5, 30. , 31.4,
       32.9, 34.3, 35.8, 37.2, 38.7, 40.1, 41.6, 43. ])

In [28]:
my_arr = np.random.randint(1,90,20)
print(my_arr)
print(f"The shape of our array is {my_arr.shape}")
print(f"The size of array is {my_arr.size}")
print(f"The max num of array is {my_arr.max()}")
print(f"The min num of array is {my_arr.min()}")
print(f"The index of small num of array is {my_arr.argmax()}") #like this we can for min 

[89 60  3 68 18 23 82 19 49 31  3 86 37 52 52 44  9 13 46 26]
The shape of our array is (20,)
The size of array is 20
The max num of array is 89
The min num of array is 3
The index of small num of array is 0


now let change the array shape 

# working process
    its like wehen you reshape then check the number of element and its size in matrix

In [ ]:
new = my_arr.reshape(5,4)   #in this ex we have 20 elemnt and we arrange in 4*5 
new

array([[89, 60,  3, 68],
       [18, 23, 82, 19],
       [49, 31,  3, 86],
       [37, 52, 52, 44],
       [ 9, 13, 46, 26]], dtype=int32)

Slicing in 2d array 

In [ ]:
#let say we want to print 60,3and 23,82 in above matrix. so 
new_array = new[0:2,1:3]
new_array
# so the logic is that like 2d array elemnt access
# we well move and instead of index we ll slice and then
# commma and then another slice 

array([[60,  3],
       [23, 82]], dtype=int32)